name: Run Postman and Load Tests

on:
  push:
    branches:
      - master  # Ou a branch que você deseja monitorar
      - qa
  pull_request:
    branches:
      - master  # Ou a branch que você deseja monitorar
      - qa

jobs:
  # Job para rodar os testes com o Newman
  postman-tests:
    runs-on: ubuntu-latest  # A máquina virtual que irá rodar o job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Faz o checkout do código no repositório

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # A versão do Node.js que você vai usar

    - name: Install dependencies
      run: npm install -g newman  # Instala o Newman globalmente

    - name: Install Newman and HTML Reporter
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run Postman tests
      run: newman run postman-collections/user-collection.json -e postman-environments/Dev-environment.json -r htmlextra --reporter-htmlextra-export newman/report.html

    - name: Upload Postman test report
      uses: actions/upload-artifact@v4
      with:
        name: postman-test-report
        path: newman/report.html  # Caminho do relatório HTML gerado

  # Job para rodar os testes de carga com o K6
  load-test:
    runs-on: ubuntu-latest
    needs: postman-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6 

      - name: Run K6 load test and generate JSON report
        run: k6 run loadTest.js --out json=result.json

      - name: Install xk6-dashboard
        run: |
          npm install -g xk6-dashboard

      - name: Convert JSON to HTML
        run: xk6-dashboard --input result.json --output report.html

      - name: Upload K6 HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-test-report
          path: report.html
